CREATE DATABASE IF NOT EXISTS studenthub;
USE studenthub;
CREATE TABLE IF NOT EXISTS users (id BIGINT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(180) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL);
CREATE TABLE IF NOT EXISTS students (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(180) NOT NULL UNIQUE, academic_year VARCHAR(30) NOT NULL, gpa DECIMAL(3,2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', INDEX idx_student_status (status), INDEX idx_student_department (department));
